CREATE DATAVASE IF NOT EXISTS scraper_db
USE scraper_db

CReate TABLE IF NOT EXISTS products (
    id VARCHAR(30) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    fat DECIMAL(5,2) DEFAULT 0 NOT NULL,
    fatSaturated DECIMAL(5,2) DEFAULT 0 NOT NULL,
    carbs DECIMAL(5,2) DEFAULT 0 NOT NULL,
    carbsSugar DECIMAL(5,2) DEFAULT 0 NOT NULL,
    protein DECIMAL(5,2) DEFAULT 0 NOT NULL,
    url TEXT NOT NULL,
    scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);